# Preprocessing Configuration for Repurpose Dataset
# This file contains all configuration settings for the preprocessing pipeline

# Directory structure
directories:
  raw_videos: "/home/yosubs/koa_scratch/repurpose/raw_videos"
  video_features: "/home/yosubs/koa_scratch/repurpose/data/video_clip_features"
  audio_features: "/home/yosubs/koa_scratch/repurpose/data/audio_pann_features"
  text_features: "/home/yosubs/koa_scratch/repurpose/data/caption_features"
  transcripts: "/home/yosubs/koa_scratch/repurpose/data/transcripts"

# Processing settings
processing:
  # Maximum number of videos to process (null for all)
  max_videos: null

  # Batch size for processing
  batch_size: 10

  # Resume processing on failure
  resume_on_failure: true

  # Clean up raw videos after feature extraction to save disk space
  cleanup_raw_videos: false

  # Parallel processing settings
  num_workers: 1

  # GPU usage
  use_gpu: true

download:
  max_workers: 1
  use_parallel: false
  rate_limit: 5.0
  max_retries: 5
  cookies_file: "/home/yosubs/koa_scratch/repurpose/www.youtube.com_cookies.txt"

# Dataset file paths
datasets:
  train: "data/train.json"
  val: "data/val.json"
  test: "data/test.json"
