datasets:
  test: data/test.json
  train: data/train.json
  val: data/val.json
directories:
  audio_features: data/audio_pann_features
  raw_videos: raw_videos
  text_features: data/caption_features
  video_features: data/video_clip_features
processing:
  batch_size: 10
  cleanup_raw_videos: false
  max_videos: 5
  resume_on_failure: true
